[book]
title = "The intermezzOS Book"
authors = ["The intermezzOS Project Developers"]
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-css = ["src/theme/extra.css"]
